ccflags-y += -Idrivers/media/platform/msm/camera_samsung
ccflags-y += -Idrivers/media/platform/msm/camera_samsung/sensor/io
obj-$(CONFIG_MSMB_CAMERA) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA) += msm_led_trigger.o
