ccflags-y += -Idrivers/media/platform/msm/camera_samsung
ccflags-y += -Idrivers/media/platform/msm/camera_samsung/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_samsung/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
