ccflags-y += -Idrivers/media/platform/msm/camera_samsung
ccflags-y += -Idrivers/media/platform/msm/camera_samsung/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_samsung/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
