ccflags-y += -Idrivers/media/platform/msm/camera_samsung
ccflags-y += -Idrivers/media/platform/msm/camera_samsung/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_samsung/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
